version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5001:5001"
    command: tail -f /dev/null
    environment:
      APP_NAME: auth-plus-notification
      APP_PORT: 5001
      GO_ENV: development
      AWS_ACCESS_KEY_ID: YOUR_AKID
      AWS_SECRET_ACCESS_KEY: YOUR_SECRET_KEY
      AWS_SESSION_TOKEN: TOKEN
      GOOGLE_APPLICATION_CREDENTIALS: /app/service-account-file.json
      GOOGLE_APPLICATION_NAME: auth-plus-c2b74
      MAILGUN_API_KEY: mailgun-api-key
      ONESIGNAL_API_KEY: onesignal-api-key
      SENDGRID_API_KEY: sendgrid-api-key
      TELEGRAM_API_KEY: your-telegram-api-key
    volumes:
      - .:/app
    restart: always
    networks:
      - notification-net
  
  database:
    container_name: postgres
    image: postgres:15.1
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: notification
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - notification-net

networks:
  notification-net:
    driver: bridge

volumes:
  v-database:
  v-metrics: