version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5001:5001"
    command: tail -f /dev/null
    env_file:
      - .env
    volumes:
      - .:/app
    restart: always
    networks:
      - host
  
  database:
    container_name: postgres
    image: postgres:11.12
    restart: always
    environment:
      POSTGRES_PASSWORD: db_password
      POSTGRES_USER: root
      POSTGRES_DB: auth
    ports:
      - '5432:5432'
    volumes:
      - v-database:/var/lib/postgres
    networks:
      - host

networks:
  host:
    driver: bridge

volumes:
  v-database: