services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    ports:
      - "5001:5001"
    command: tail -f /dev/null
    env_file: ".env"
    volumes:
      - .:/app
    restart: always
    networks:
      - notification-net

networks:
  notification-net:
    driver: bridge
