global:
  scrape_interval: 5s
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "auth-plus-main"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:5001", "host.docker.internal:5001"]
  - job_name: node
    static_configs:
      - targets: ["localhost:9100"]
