name: Continuous Delivery on Merge
on:
  push:
    branches: main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Use right version of golang
        uses: actions/setup-go@v2
        with:
          go-version: "^1.19"
      - name: Execute test
        run: make test/ci
